### ISSUE TITLE
not getting all details 

### ISSUE THREAD

**Issue by eliranc22** [YossiSassi/Get-ADGroupChanges#1]
Hi,

is there a time limit for searching? 

thanks,

**Comment by YossiSassi** [comment]
Hi,
There should be no limit, in terms of 'when' the group change happened - the script looks for changes since the dawn of the domain, since the Domain was created.

Sometimes, for objects with special chars (e.g. <>) in their common name, the xml parser is having trouble, so I might display partial info on *that specific object*.
It this what you are referring to?

Can you be more specific about what details you are missing? 
What is the command you are running/using which parameters?

**Comment by eliranc22** [comment]
Hi Yossi,

thanks for your response. 
I'm running the command "Get-ADGroupChanges -GroupName 'domain admins' -Output CSV" but I'm not seeing all the users that have been removed from the group,  I can see user that has been removed one year ago but I don't see user that removed 3-4 months ago. 

thanks,

**Comment by YossiSassi** [comment]
Thanks Eliran.

Interesting.. Can you please run the following command, and send the output, excluding of course, any sensitive/internal info? 
just wondering is different results are received between DCs:

$DCs = (Get-ADDomainController -Filter *).name; $DCs | foreach {$DC=$_; $ReplMD = (Get-ADGroup "domain admins" -Server $DC -Properties 'msds-replvaluemetadata').'msds-replvaluemetadata'; "Total repl changes for this group on DC $DC is $($ReplMD.count)";$ReplMD}

Thanks!

**Comment by eliranc22** [comment]
I did the check, and all DC's have the same amount of changes - 26 (there was far more that 26 changes).  
if you still need the output I'll need to delete some sensitive info.

thanks,

**Comment by YossiSassi** [comment]
Yes - can you please send it over to yossis@protonmail.com ? 
the output of the command I wrote above + the csv output from the command. all without user names etc, of course. 
I will look into it.
Thanks!

**Comment by YossiSassi** [comment]
Hi Eliran,

Just following up on some old threads :)

Did you have a chance to use the script lately?
https://github.com/yossisassi/get-ADGroupChanges/i

Few months back I had an updated version, including offline support (querying an ntds.dit copy) and some fixes.
I'd be happy if you can give it another run and send feedback.

Thanks!

------- Original Message -------
